final Map<String, Map<String, String>> countries = {
  "AD": {"fr": "Andorre", "en": "Andorra"},
  "AE": {"fr": "Émirats arabes unis", "en": "United Arab Emirates"},
  "AF": {"fr": "Afghanistan", "en": "Afghanistan"},
  "AG": {"fr": "Antigua-et-Barbuda", "en": "Antigua and Barbuda"},
  "AL": {"fr": "Albanie", "en": "Albania"},
  "AM": {"fr": "Arménie", "en": "Armenia"},
  "AO": {"fr": "Angola", "en": "Angola"},
  "AR": {"fr": "Argentine", "en": "Argentina"},
  "AT": {"fr": "Autriche", "en": "Austria"},
  "AU": {"fr": "Australie", "en": "Australia"},
  "AZ": {"fr": "Azerbaïdjan", "en": "Azerbaijan"},
  "BA": {"fr": "Bosnie-Herzégovine", "en": "Bosnia and Herzegovina"},
  "BB": {"fr": "Barbade", "en": "Barbados"},
  "BD": {"fr": "Bangladesh", "en": "Bangladesh"},
  "BE": {"fr": "Belgique", "en": "Belgium"},
  "BF": {"fr": "Burkina Faso", "en": "Burkina Faso"},
  "BG": {"fr": "Bulgarie", "en": "Bulgaria"},
  "BH": {"fr": "Bahreïn", "en": "Bahrain"},
  "BI": {"fr": "Burundi", "en": "Burundi"},
  "BJ": {"fr": "Bénin", "en": "Benin"},
  "BN": {"fr": "Brunei", "en": "Brunei"},
  "BO": {"fr": "Bolivie", "en": "Bolivia"},
  "BR": {"fr": "Brésil", "en": "Brazil"},
  "BS": {"fr": "Bahamas", "en": "Bahamas"},
  "BT": {"fr": "Bhoutan", "en": "Bhutan"},
  "BW": {"fr": "Botswana", "en": "Botswana"},
  "BY": {"fr": "Biélorussie", "en": "Belarus"},
  "BZ": {"fr": "Belize", "en": "Belize"},
  "CA": {"fr": "Canada", "en": "Canada"},
  "CD": {"fr": "République démocratique du Congo", "en": "Congo (Kinshasa)"},
  "CF": {"fr": "République centrafricaine", "en": "Central African Republic"},
  "CG": {"fr": "République du Congo", "en": "Congo (Brazzaville)"},
  "CH": {"fr": "Suisse", "en": "Switzerland"},
  "CI": {"fr": "Côte d'Ivoire", "en": "Côte d'Ivoire"},
  "CL": {"fr": "Chili", "en": "Chile"},
  "CM": {"fr": "Cameroun", "en": "Cameroon"},
  "CN": {"fr": "Chine", "en": "China"},
  "CO": {"fr": "Colombie", "en": "Colombia"},
  "CR": {"fr": "Costa Rica", "en": "Costa Rica"},
  "CU": {"fr": "Cuba", "en": "Cuba"},
  "CV": {"fr": "Cap-Vert", "en": "Cabo Verde"},
  "CY": {"fr": "Chypre", "en": "Cyprus"},
  "CZ": {"fr": "République tchèque", "en": "Czech Republic"},
  "DE": {"fr": "Allemagne", "en": "Germany"},
  "DJ": {"fr": "Djibouti", "en": "Djibouti"},
  "DK": {"fr": "Danemark", "en": "Denmark"},
  "DM": {"fr": "Dominique", "en": "Dominica"},
  "DO": {"fr": "République dominicaine", "en": "Dominican Republic"},
  "DZ": {"fr": "Algérie", "en": "Algeria"},
  "EC": {"fr": "Équateur", "en": "Ecuador"},
  "EE": {"fr": "Estonie", "en": "Estonia"},
  "EG": {"fr": "Égypte", "en": "Egypt"},
  "ER": {"fr": "Érythrée", "en": "Eritrea"},
  "ES": {"fr": "Espagne", "en": "Spain"},
  "ET": {"fr": "Éthiopie", "en": "Ethiopia"},
  "FI": {"fr": "Finlande", "en": "Finland"},
  "FJ": {"fr": "Fidji", "en": "Fiji"},
  "FM": {"fr": "Micronésie", "en": "Micronesia"},
  "FR": {"fr": "France", "en": "France"},
  "GA": {"fr": "Gabon", "en": "Gabon"},
  "GB": {"fr": "Royaume-Uni", "en": "United Kingdom"},
  "GD": {"fr": "Grenade", "en": "Grenada"},
  "GE": {"fr": "Géorgie", "en": "Georgia"},
  "GH": {"fr": "Ghana", "en": "Ghana"},
  "GM": {"fr": "Gambie", "en": "Gambia"},
  "GN": {"fr": "Guinée", "en": "Guinea"},
  "GQ": {"fr": "Guinée équatoriale", "en": "Equatorial Guinea"},
  "GR": {"fr": "Grèce", "en": "Greece"},
  "GT": {"fr": "Guatemala", "en": "Guatemala"},
  "GW": {"fr": "Guinée-Bissau", "en": "Guinea-Bissau"},
  "GY": {"fr": "Guyana", "en": "Guyana"},
  "HN": {"fr": "Honduras", "en": "Honduras"},
  "HR": {"fr": "Croatie", "en": "Croatia"},
  "HT": {"fr": "Haïti", "en": "Haiti"},
  "HU": {"fr": "Hongrie", "en": "Hungary"},
  "ID": {"fr": "Indonésie", "en": "Indonesia"},
  "IE": {"fr": "Irlande", "en": "Ireland"},
  "IL": {"fr": "Israël", "en": "Israel"},
  "IN": {"fr": "Inde", "en": "India"},
  "IQ": {"fr": "Irak", "en": "Iraq"},
  "IR": {"fr": "Iran", "en": "Iran"},
  "IS": {"fr": "Islande", "en": "Iceland"},
  "IT": {"fr": "Italie", "en": "Italy"},
  "JM": {"fr": "Jamaïque", "en": "Jamaica"},
  "JO": {"fr": "Jordanie", "en": "Jordan"},
  "JP": {"fr": "Japon", "en": "Japan"},
  "KE": {"fr": "Kenya", "en": "Kenya"},
  "KG": {"fr": "Kirghizistan", "en": "Kyrgyzstan"},
  "KH": {"fr": "Cambodge", "en": "Cambodia"},
  "KI": {"fr": "Kiribati", "en": "Kiribati"},
  "KM": {"fr": "Comores", "en": "Comoros"},
  "KN": {"fr": "Saint-Christophe-et-Niévès", "en": "Saint Kitts and Nevis"},
  "KP": {"fr": "Corée du Nord", "en": "Korea, North"},
  "KR": {"fr": "Corée du Sud", "en": "Korea, South"},
  "KW": {"fr": "Koweït", "en": "Kuwait"},
  "KZ": {"fr": "Kazakhstan", "en": "Kazakhstan"},
  "LA": {"fr": "Laos", "en": "Laos"},
  "LB": {"fr": "Liban", "en": "Lebanon"},
  "LC": {"fr": "Sainte-Lucie", "en": "Saint Lucia"},
  "LI": {"fr": "Liechtenstein", "en": "Liechtenstein"},
  "LK": {"fr": "Sri Lanka", "en": "Sri Lanka"},
  "LR": {"fr": "Libéria", "en": "Liberia"},
  "LS": {"fr": "Lesotho", "en": "Lesotho"},
  "LT": {"fr": "Lituanie", "en": "Lithuania"},
  "LU": {"fr": "Luxembourg", "en": "Luxembourg"},
  "LV": {"fr": "Lettonie", "en": "Latvia"},
  "LY": {"fr": "Libye", "en": "Libya"},
  "MA": {"fr": "Maroc", "en": "Morocco"},
  "MC": {"fr": "Monaco", "en": "Monaco"},
  "MD": {"fr": "Moldavie", "en": "Moldova"},
  "ME": {"fr": "Monténégro", "en": "Montenegro"},
  "MG": {"fr": "Madagascar", "en": "Madagascar"},
  "MH": {"fr": "Îles Marshall", "en": "Marshall Islands"},
  "MK": {"fr": "Macédoine du Nord", "en": "North Macedonia"},
  "ML": {"fr": "Mali", "en": "Mali"},
  "MM": {"fr": "Birmanie (Myanmar)", "en": "Myanmar"},
  "MN": {"fr": "Mongolie", "en": "Mongolia"},
  "MR": {"fr": "Mauritanie", "en": "Mauritania"},
  "MT": {"fr": "Malte", "en": "Malta"},
  "MU": {"fr": "Maurice", "en": "Mauritius"},
  "MV": {"fr": "Maldives", "en": "Maldives"},
  "MW": {"fr": "Malawi", "en": "Malawi"},
  "MX": {"fr": "Mexique", "en": "Mexico"},
  "MY": {"fr": "Malaisie", "en": "Malaysia"},
  "MZ": {"fr": "Mozambique", "en": "Mozambique"},
  "NA": {"fr": "Namibie", "en": "Namibia"},
  "NE": {"fr": "Niger", "en": "Niger"},
  "NG": {"fr": "Nigeria", "en": "Nigeria"},
  "NI": {"fr": "Nicaragua", "en": "Nicaragua"},
  "NL": {"fr": "Pays-Bas", "en": "Netherlands"},
  "NO": {"fr": "Norvège", "en": "Norway"},
  "NP": {"fr": "Népal", "en": "Nepal"},
  "NR": {"fr": "Nauru", "en": "Nauru"},
  "NZ": {"fr": "Nouvelle-Zélande", "en": "New Zealand"},
  "OM": {"fr": "Oman", "en": "Oman"},
  "PA": {"fr": "Panama", "en": "Panama"},
  "PE": {"fr": "Pérou", "en": "Peru"},
  "PG": {"fr": "Papouasie-Nouvelle-Guinée", "en": "Papua New Guinea"},
  "PH": {"fr": "Philippines", "en": "Philippines"},
  "PK": {"fr": "Pakistan", "en": "Pakistan"},
  "PL": {"fr": "Pologne", "en": "Poland"},
  "PS": {"fr": "Palestine", "en": "Palestine"},
  "PT": {"fr": "Portugal", "en": "Portugal"},
  "PW": {"fr": "Palaos", "en": "Palau"},
  "PY": {"fr": "Paraguay", "en": "Paraguay"},
  "QA": {"fr": "Qatar", "en": "Qatar"},
  "RO": {"fr": "Roumanie", "en": "Romania"},
  "RS": {"fr": "Serbie", "en": "Serbia"},
  "RU": {"fr": "Russie", "en": "Russia"},
  "RW": {"fr": "Rwanda", "en": "Rwanda"},
  "SA": {"fr": "Arabie saoudite", "en": "Saudi Arabia"},
  "SB": {"fr": "Îles Salomon", "en": "Solomon Islands"},
  "SC": {"fr": "Seychelles", "en": "Seychelles"},
  "SD": {"fr": "Soudan", "en": "Sudan"},
  "SE": {"fr": "Suède", "en": "Sweden"},
  "SG": {"fr": "Singapour", "en": "Singapore"},
  "SI": {"fr": "Slovénie", "en": "Slovenia"},
  "SK": {"fr": "Slovaquie", "en": "Slovakia"},
  "SL": {"fr": "Sierra Leone", "en": "Sierra Leone"},
  "SM": {"fr": "Saint-Marin", "en": "San Marino"},
  "SN": {"fr": "Sénégal", "en": "Senegal"},
  "SO": {"fr": "Somalie", "en": "Somalia"},
  "SR": {"fr": "Suriname", "en": "Suriname"},
  "SS": {"fr": "Soudan du Sud", "en": "South Sudan"},
  "ST": {"fr": "Sao Tomé-et-Principe", "en": "Sao Tome and Principe"},
  "SV": {"fr": "Salvador", "en": "El Salvador"},
  "SY": {"fr": "Syrie", "en": "Syria"},
  "SZ": {"fr": "Eswatini", "en": "Eswatini"},
  "TD": {"fr": "Tchad", "en": "Chad"},
  "TG": {"fr": "Togo", "en": "Togo"},
  "TH": {"fr": "Thaïlande", "en": "Thailand"},
  "TJ": {"fr": "Tadjikistan", "en": "Tajikistan"},
  "TL": {"fr": "Timor oriental", "en": "Timor-Leste"},
  "TM": {"fr": "Turkménistan", "en": "Turkmenistan"},
  "TN": {"fr": "Tunisie", "en": "Tunisia"},
  "TO": {"fr": "Tonga", "en": "Tonga"},
  "TR": {"fr": "Turquie", "en": "Turkey"},
  "TT": {"fr": "Trinité-et-Tobago", "en": "Trinidad and Tobago"},
  "TV": {"fr": "Tuvalu", "en": "Tuvalu"},
  "TW": {"fr": "Taiwan", "en": "Taiwan"},
  "TZ": {"fr": "Tanzanie", "en": "Tanzania"},
  "UA": {"fr": "Ukraine", "en": "Ukraine"},
  "UG": {"fr": "Ouganda", "en": "Uganda"},
  "US": {"fr": "États-Unis", "en": "United States"},
  "UY": {"fr": "Uruguay", "en": "Uruguay"},
  "UZ": {"fr": "Ouzbékistan", "en": "Uzbekistan"},
  "VA": {"fr": "Vatican", "en": "Vatican City"},
  "VC": {"fr": "Saint-Vincent-et-les-Grenadines", "en": "Saint Vincent and the Grenadines"},
  "VE": {"fr": "Venezuela", "en": "Venezuela"},
  "VN": {"fr": "Viêt Nam", "en": "Vietnam"},
  "VU": {"fr": "Vanuatu", "en": "Vanuatu"},
  "WS": {"fr": "Samoa", "en": "Samoa"},
  "YE": {"fr": "Yémen", "en": "Yemen"},
  "ZA": {"fr": "Afrique du Sud", "en": "South Africa"},
  "ZM": {"fr": "Zambie", "en": "Zambia"},
  "ZW": {"fr": "Zimbabwe", "en": "Zimbabwe"},
};